# Generated by Django 5.0 on 2024-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=100)),
                ('task_model', models.ManyToManyField(to='add_task.add_task')),
            ],
        ),
    ]
