# Generated by Django 5.0 on 2024-01-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_category',
            name='task_model',
        ),
    ]
