# Generated by Django 5.0 on 2024-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_tile', models.CharField(max_length=150)),
                ('task_description', models.TextField()),
                ('task_assign_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
