# Generated by Django 5.0 on 2024-01-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0002_rename_is_complete_add_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_task',
            old_name='task_tile',
            new_name='task_title',
        ),
    ]
