# Generated by Django 5.0 on 2024-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_category', '0002_remove_add_category_task_model'),
        ('add_task', '0003_rename_task_tile_add_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task',
            name='Category',
            field=models.ManyToManyField(to='add_category.add_category'),
        ),
    ]
